module: IndefiniteObservable
module_version: 2.0.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - IndefiniteObservable.xcworkspace
  - -scheme
  - IndefiniteObservable
github_url: https://github.com/material-motion/indefinite-observable-swift
github_file_prefix: https://github.com/material-motion/indefinite-observable-swift/tree/v2.0.0
